# Discussion

Biomedical longitudinal non-linear data is particularly challenging to analyze due to the likelihood of missing observations and different correlation structures in the data, which limit the use of rm-ANOVA. Although LMEMs have started to replace rm-ANOVA models to analyze biomedical data, we have visually demonstrated in Section \@ref(simulation) that both methods yield biased estimates when they are used to fit non-linear data, in what is known as "Type III" error [@dennis2019]. This is particularly important because although the _p-value_ is the common measure of statistical significance, the validity of its interpretation is determined by the agreement of the data and the model. Guidelines for statistical reporting in biomedical journals exist (the SAMPL guidelines) [@lang2015] but they have not been widely adopted and in the case of longitudinal data, we consider that researchers would benefit from reporting a visual assessment of the correspondence between the model fit and the data, instead of simply reporting an $R^2$ value.

In this paper we have presented GAMs as a suitable method to analyze non-linear longitudinal data. It is interesting to note that although GAMs are a well established method to analyze temporal data in different fields (among which are palaeoecology, geochemistry, and ecology) [@hefley2017; @pedersen2019] they are not routinely used in biomedical research despite a publication from Trevor and Hastie that demonstrated their use in medical research [@hastie1995]. This is possibly due to the fact that the theory behind GAMs can seem very different from that of rm-ANOVA and LMEMs, but the purpose of Section \@ref(GAM-theory) is to demonstrate that at its core it is quite simple: Instead of using a linear relationship to model the response (as rm-ANOVA and LMEMs do), GAMs use basis functions to build smooths that are capable of following non-linear trends in the data.

However, from a practical standpoint is equally important to demonstrate how GAMs are implemented. We have provided an example on how GAMs can be fitted using simulated data that follows trends reported in biomedical literature [@vishwanath2009] using $\textsf{R}$ and the package _mgcv_[@wood2017] in Section \@ref(longitudinal-GAMs), while a basic workflow for model selection is in the Appendix. One of the features of GAMs is that they go beyond a mere _p-value_ to estimate differences between groups and can provide a time-based estimate of shifts in the response that can be directly tied to biological values. Because the analysis of GAMs is more computationally intensive when compared to traditional linear models, $\textsf{R}$ is the software of choice because it not only provides a fully developed environment to fit thse models, but eases simulation and provides powerful and convenient methods of visualization, which are key aspects that biomedical researchers might need to consider to make their work reproducible. 

In this regard, reproducibility is still an issue in biomedical research [@begley2015;@weissgerber2018], but it is becoming apparent that what other disciplines have experienced in this aspect is likely to impact soon rather than later this field. Researchers need to plan on how they will make their data, code, and any other materials open and accesible as more journals and funding agencies recognize the importance and benefits of open science in biomedical research. In this paper, we have shared all the data and code in order to make our work reproducible, and we hope that this will encourage other researchers to 
