
# Conclusion

Longitudinal studies in biomedical research have been traditionally analyzed using a rm-ANOVA approach. 

The traditional methods to analyze biomedical longitudinal data (rm-ANOVA, LMEMs) are restricted to cases when the data follows a linear pattern. When the trend of the data is non-linear (as it is frequently the case in biomedical research), the use of rm-ANOVA and LMEMs leads to unreliable inference and biased estimates. GAMs present a suitable alternative to analyze non-linear longitudinal biomedical data, as they overcome the limitations of linearity, compound symmetry, and missing observations imposed by traditional methods. By  presenting in a clear and visual manner the limitations of rm-ANOVA and LMEMs, and the implementation of GAMs using simulated data that follows previously reported trends in the literature, we aim at encouraging biomedical researchers to consider different statistical tools to analyze longitudinal data. Finally, by providing the data and code used in this paper we hope to address the need of creating and sharing reproducible work in biomedical research.
