# Discussion

Biomedical longitudinal data is particularly challenging to analyze due to the likelihood of missing observations and different correlation structures in the data, which limit the use of rm-ANOVA. Although LMEMs can handle missing observations and different correlation structures, both LMEMs and rm-ANOVA yield biased estimates when they are used to fit data with non-linear trends as we have visually demonstrated in Section \@ref(simulation), where it is clear that these models do not capture the non-linear trend of the data, thereby causing a "model misspecification error". 

This "model misspecification" error, also is known as a "Type III" error [@dennis2019] is particularly important because although the _p-value_ is the common measure of statistical significance, the validity of its interpretation is determined by the agreement of the data and the model. Polynomial effects can be used in LMEMs, and it could be argued that in Section \@ref(simulation) a LMEM with quadratic effects could have been fitted, but in reality the true function in the data is not known; using polynomial effects presents more questions than answers in this case (i.e., what is the appropriate polynomial effect to use? quadratic?, cubic?, what is the biological interpretation of a polynomial effect?). Moreover, polynomial effects have other associated issues that we have described in Section \@ref(GAM-theory). 

Guidelines for statistical reporting in biomedical journals exist (the SAMPL guidelines) [@lang2015] but they have not been widely adopted and in the case of longitudinal data, we consider that researchers would benefit from reporting a visual assessment of the correspondence between the model fit and the data, rather than merely relying on a $R^2$ value, which is not meaningful in the case of a Type III error.

In this paper we have presented GAMs as a suitable method to analyze longitudinal data with non-linear trends.  
It is interesting to note that although GAMs are a well established method to analyze temporal data in different fields (among which are palaeoecology, geochemistry, and ecology) [@hefley2017; @pedersen2019] they are not routinely used in biomedical research despite an early publication from Hastie and Tibshirani that demonstrated their use in medical research [@hastie1995]. This is possibly due to the fact that the theory behind GAMs can seem very different from that of rm-ANOVA and LMEMs, but the purpose of Section \@ref(GAM-theory) is to demonstrate that at its core the principle is quite simple: Instead of using a linear relationship to model the response (as rm-ANOVA and LMEMs do), GAMs use basis functions to build smooths that are capable of learning non-linear trends in the data, which is a major advantage over models where the user has to know the non-linear relationship _a priori_ in order to provide it to the model (i.e., polynomial effects in LMEMs).

However, from a practical standpoint is equally important to demonstrate how GAMs are computationally implemented. We have provided an example on how GAMs can be fitted using simulated data that follows trends reported in biomedical literature [@vishwanath2009] using $\textsf{R}$ and the package _mgcv_[@wood2017] in Section \@ref(longitudinal-GAMs), while a basic workflow for model selection is in the [Appendix](#workflow). One of the features of GAMs is that their Bayesian interpretation allows to indicate differences between groups without the need of a _p-value_, and in turn provide a time-based estimate of shifts in the response that can be directly tied to biological values as the pairwise smooth comparisons in Figure  \@ref(fig:plot-pairwise-comp) indicate. The model is therefore able to identify changes between the groups at time points were data was not directly measured even with missing data exists ( $\approx$ day 3 in Figure \@ref(fig:plot-pairwise-comp) A, B ), which can be used by researchers as feedback on experiment design and to further evaluate important biological changes in future studies. 

We have used $\textsf{R}$ as the software of choice for this paper because not only provides a fully developed environment to fit GAMs, but also eases simulation (which is becoming increasingly used for exploratory statistical analysis and power calculations) and provides powerful and convenient methods of visualization, which are key aspects that biomedical researchers might need to consider to make their work reproducible. In this regard, reproducibility is still an issue in biomedical research [@begley2015;@weissgerber2018], but it is becoming apparent that what other disciplines have experienced in this aspect is likely to impact sooner rather than later this field. Researchers need to plan on how they will make their data, code, and any other materials open and accessible as more journals and funding agencies recognize the importance and benefits of open science in biomedical research. We have made all the data and code used in this paper accessible, and we hope that this will encourage other researchers to do the same with future projects.
