---
title: |
    | **Generalized additive models to analyze biomedical non-linear longitudinal data in R:**
    | Beyond repeated measures ANOVA and Linear Mixed Models
    | 
    | Journal of Submission: Statistics in Medicine
    | Manuscript ID: SIM-21-0640
header-includes:
    \usepackage{placeins}
output:  
  bookdown::pdf_document2:
    #template: my-template.tex #if a custom template that removes the additional "and" in the author information is desired
    pandoc_args: --listings #calls the listings package to fit code within the page margins
    keep_tex: yes #keep LaTeX file for submission
    fig_caption: yes #allows captions in figures
    toc: false #do not include table of contents
    number_sections: false #do not number sections
    extra_dependencies:
      subfig: null #allows for subfigures
      breqn: null #line breaks for long equations
      caption: ["font={small}"] #size of the figure captions
      #float: null #allows for control of placement of figures
    includes:
      in_header: latex_docs/preamble_Appendix.sty #additional LaTeX formatting
#csl: elsevier-with-titles.csl #style for references
#bibliography: refs.bib #references
link-citations: yes #adds links to the citations
'': default
---


# General Comments to the Reviewers

We would like to thank the reviewer for the careful and thorough analysis of this manuscript to _Statistics in Medicine_ and for the thoughtful comments and constructive suggestions, which helped improve the quality of this manuscript. We carefully considered the reviewer’s comments and in this document, explain how we revised the manuscript based on those comments and suggestions. 


# General Comments to the Editor

Dr. Platt, 

The authors thank you for your determination that our manuscript may be suitable for resubmission in _Statistics in Medicine_ after addressing the reviewer's comments. To this end, we have addressed all critiques. We hope these revisions, submitted on December 5, 2021, improve the manuscript so it is deemed worthy of publication in _Statistics in Medicine_. Following are our detailed responses to reviewer comments.

## Reviewer's Introduction
Mundo and colleagues present a tutorial on the use of generalized additive models to analyze longitudinal data. A comparison with repeated measures ANOVA and linear mixed models is provided and a recurring example using simulated
data is used to illustrate the differences among the methods and the advantages of GAM. While I like the general approach and aim of the manuscript, there are a number of inaccuracies and omissions, especially in the discussion of GAMs that make it difficult for me to support publication at this stage. I believe — given evidence elsewhere in the manuscript that the authors really do know the subject — that these inaccuracies and omissions stem from preparing a tutorial in a scientific paper format where word-length considerations come into play. Below I outline the main areas where I feel the GAM methodology is inaccurately presented or important topics omitted, and make suggestions to improve the manuscript.

## \textcolor{reviewersblue} {Reply to Introduction}
We appreciate Dr. Simpson's comments and critiques to our manuscript.

# Comments from reviewers

# Missing data

## Reviewer's Comments

I found this use of “missing” data to be a little confusing. I understand what the authors are getting at, but it suggests that GAMs can handle this whereas rm-ANOVA and LMMs can’t. While I appreciate that rm-ANOVA might require
balanced observations for the group errors, LMMs are just as able to handle “missingness” (in the sense implied by the authors) as GAMs are. Additionally, the “missingness” isn’t meant solely as missing in the statistical sense, but really it is due to irregular or incomplete sampling, more generally.
It would be helpful to make the discussion of missingness about balanced data and to try to avoid terms like “missing” as that may be inferred to suggest GAMs and LMMs are immune to missing data problems (they aren’t), they
just don’t require balance.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

We appreciate the comments about clarity in the use of the term "missingness". Please note that the title for Section 3.4 has been changed from "Missing observations" to "Unbalanced data". We have restructured this section in the following manner:

- The term "missing data" has been removed to avoid confusion. We now refer to different number of observations as "unbalanced data" (L201-204).

- We have made clear that LMEMs can also work with missing observations (L209)

- Emphasis has been provided to the fact that GAMs are not immune to missing data problems, and that researchers need to minimize missing observation rates (L217-220).


# Unnecesary restriction of LMMs

## Reviewer's Comments

Why not use quadratic effects of time in the LMM? I appreciate this would make the model more complex, but trying to fit a quadratic effect with a linear model strikes me as futile and somewhat of a straw person argument to make.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

We appreciate the reviewer's perspective regarding the somewhat contradictory argument of fitting a linear effects LMM to quadratic data. However, this is an intentional approach because we follow the statistical analysis logic followed by most biomedical researchers to analyze longitudinal data: Fit a LMM or an rm-ANOVA, and if you get significant _p-values_ that's good enough. The purpose of the figure is to convey that changing models (from rm-ANOVA to LMEM) without visualizing the model fit is in this case is something that will propagate bias in the results and does not provide any substantial improvement. However, we acknowledge that this point was not explicitly stated in the original manuscript and the following changes have been made:

- L95: We mention that LMEMs assume a linear relationship "by default", but we indicate that polynomial effects can be used as well, though they have their own shortcomings.

- L119-L120 now reads "the limitations of LMEMs and rm-ANOVA regarding an expected trend in the response", instead of "linearity of response" (L119 in the original manuscript).

- L136 now reads "assumed relationship" instead of  "linear relationship" (L135 in the original manuscript).

- Section 3.2 now is titled "Assumed relationship" instead of "Linear relationship"

- L181-L184 now indicate that polynomial effects can be used in a LMEM, but that they have little predictive power and lack biological or mechanistic interpretation.

- We provide additional context on the purpose of using linear models to fit quadratic data in L250-L251 which now read "We are aware that the simulated data used in this section present an extreme case that might not occur frequently in biomedical research, but they are used to 1) present the consequences of modeling non-linear trends in data with a linear model such as rm-ANOVA or a LMEM with "default" (linear) effects and, 2) demonstrate that, a visual assessment of model fit is an important tool that helps determine the validity of any statistical assumptions."

We believe that the aforementioned change makes a clear statement to the reader about our intentions in Fig.1. We want to emphasize that strictly speaking the term "default" might not be correct, but we are stretching the language to make the point that doing a simple switch from rm-ANOVA to a LMEMs (in R) without any additional changes results in the assumption of linear effects that still provide biased estimates.

- L273-276 now include some of the reasons that complicate the use of polynomial effects in a LMEM for the data in Fig. 1. Specifically, that in reality the true function is not known and that this complicates choosing the degree of the polynomial. We also reference Section 4.3.1, which provides more detail on the limitation of polynomial effects.

- In Section 6 (Discussion)  we emphasize again the rationale for not using polynomial effects on the LMEM in Fig. 1 (L509-513). 


# GLMMs

## Reviewer's Comments

You don’t even mention generalized linear mixed models; why? In the context of the tutorial they represent the logical bridge between GAM and LMM, especially when you consider that you are really fitting GAMMs here.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

- We appreciate Dr. Simpson's comment here and the equations provided, which we have now incorporated in the manuscript.. We acknowledge that a brief overview of the different statistical model classes was missing in the original manuscript, and we have now extensively edited Section 4 to provide context on LMs, GLMs and GLMMs before introducing GAMs. The changes now appear between L282 (where Section 4 has been renamed to "Linear Models and Beyond") and L321. Because the different model classifications are not commonly known in the biomedical field, we contextualize the previously presented rm-ANOVA and LMEM into their respective classes to provide the reader with a clear understanding of where each model fits and also of where GAMs fit within this framework. We believe this properly addressed the reviewer comments.

- We also acknowledge that the GAM model (Equation 5 in the original manuscript and Equation 10 in the revised document) corresponds to the **linear case**. This change will avoid the propagation of confusion that Dr. Simpson correctly indicated in his comment.

- We have also changed L328 to indicate that the term $\varepsilon_{ijt}$ is the residual, and not a separable error. Of notice, we are following the notation provided by Dr. Simpson in Eq. 3 in the paper "Modelling Modelling Palaeoecological Time Series Using Generalised Additive Models". **do we need this here? I am adding it because we are following the same model specification that he has in this paper**

# Thin plate regression splines

## Reviewer's Comments

The authors define the default basis in {mgcv}, the software being used here to illustrate fitting GAMs, as “…thin plate regression splines are an optimized version that work well with noisy data.” This is not a good description of what a thin plate regression spline (hereafter TPRS) is, and is not a good description of what the low-rank versions in {mgcv} are.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

The following changes have been made:

- The information on L289-294 pertaining splines has been changed. L301-309 now describe cubic splines (CS), thin plate splines (TPS) and thin plate regression splines (TPRS) in a manner that conveys their general properties and advantages (or disadvantages) to a non-Statistical reader.  

## Reviewer's Comments

Much better, I believe, is to talk about this in terms of basis functions, of which there are five in this example. You can use the same terminology to refer to the CRS basis, and others. That in the CRS if you want _k_ basis functions you need _k_ knots (IIRC). CRS require you to specify the knot locations (or let the software spread them evenly through the data); TPRS don’t.
Hence the paragraph starting on L195 is confusing and misleading. The basis functions are not piece-wise polynomial and there are not “region[s] where a different set of basis functions will be used”. Indeed, the functions you show
operate throughout the range of the covariate.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

- L297-300 no longer refer to "knots" when referring to the construction of the smooth, now indicating that the number of _basis functions_ is what is specified when constructing the smoother. In the updated manuscript, this change appears in L310-315, and is more clear to the reader due to the changes introduced in L301-L309.


# Penalised splines
## Reviewer's Comments

You talk a little about “wiggliness” and penalising the weights for each basis function towards 0 but you don’t really explain this most crucial concept of the model fitting problem and why modern GAMs are so much better than the GAMs developed by Hastie and Tibshirani when they first introduced GAMs to the world.
You really need to define wiggliness beyond something that is used to avoid overfitting. Typically it is squared second derivative of the estimated function; so we limit the curvature of the fitted function by default. Technically the penalty is the penalty matrix - it is a matrix and it is fixed once we define the basis functions. What isn’t fixed is (are) the smoothness parameter(s) of the smooth; it is those that control how much penalty we subtract from the log-likelihood of the data given the model estimates. To speak of a “weak” or “strong” penalty was a little confusing for me.
Hence fitting a GAM requires one to estimate parameters and one or more smoothness parameters for each smooth in the GAM, plus any parameters required for parametric terms.
By glossing over these important concepts, the reader is left wondering what wiggliness is, how we measure overfit? etc.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

# Bayesian

## Reviewer's Comments

GAMs in {mgcv} are considered to be empirical Bayesian models, but in general GAMs can be fully Bayesian. You can fit fully Bayesian GAMs using INLA and JAGS using functions from {mgcv}, and the {brms} package allows full Bayesian GAMs to be estimated simply using Stan for example. This needs to be clarified.
I’m not really sure what you mean by the sentence beginning “Moreover, the use of the restricted maximum…”. I think I get what you mean; by casting the wiggly parts of smooths as random effects we can estimate the fit using REML
and standard linear mixed model software. However, you can fit the model using the full fat version of maximum likelihood and these models would still be empirical Bayes if fitted by {mgcv}.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

- We have clarified the concept "empirical Bayesian", which appeared on L318-L319 in the original manuscript. In the revised manuscript, L335-338 now indicate that Stan, JAGS or other probabilistic programming language can be used to estimate GAMs using a full Bayesian approach.

- The sentence "Moreover, the use of the restricted maximum likelihood (REML) to estimate the smoothing parameters gives an empirical estimate of the smooth model", which appears in L319 in the original manuscript has been removed from the text. Instead, the concept of REML has been moved to Section 6.2 L392-395, where we state some of the reasons indicated by Wood when choosing restricted maximum likelihood (REML) over the default general cross validation (GCV) method for smooth parameter estimation in _mgcv_. 


# Coverage of confidence intervals

## Reviewer's Comments

This entire section from L320 onward through to the end of Section 5 needs some work. When viewed from the Bayesian perspective, the intervals are Bayesian credible intervals. When viewed from a frequentist perspective, the same intervals are confidence intervals but instead of having the typical point-wise interpretation they have an across the function interpretation. 
The description of what this means is wrong — you are almost giving the incorrect definition of a confidence interval here. The interval either does or does not contain the true function. That is given. I’m sure this is just a slip then on L324-325.
Also, your description implies a simultaneous interval, although I don’t think you intended this. One could interpret “95% of the time” as meaning 95% of the functions are contained in their entirety.

What across-the-function means is simply that if we average the coverage of the interval over the entire function we get approximately the nominal coverage, 95% say. For this to occur then, some areas of the function must have more
than nominal coverage and some areas less than the nominal coverage.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

The content in L320-329 regarding confidence intervals (CIs) in the original submission has been changed in the following manner:

- L341-L355 now contain a more detailed and accurate explanation on the differences and interpretation of "poin-twise" CIs and "across-the-function" CIs. We removed the "95% of the time" phrase to avoid confusion, and instead we provide an explanation that focuses on random sampling: "if 100 random samples are obtained and a GAM and CI is calculated for each one of them, it would be expected that 95 out of the 100 fitted CIs entirely contain the true function" (L352-354). We also reference the work of Marra and Wood if the reader desires a more in-depth exploration of across the function CIs.

# Differences in smooths

## Reviewer's Comments

The essence of this is not “if the difference between [credible] intervals of the fitted smooths… is non-zero”. For a variety of reasons this is not how it works. Instead we compute the difference of the smooths and then compute a credible interval around this difference. Also, to interpret this correctly we really need to do a simultaneous interval as you are looking at all points over the range of the covariate. If we just use the usual interval we have to consider the under and over coverage of the Nychka across-the-function intervals. You should talk about this issue in this section if you don’t compute simultaneous intervals.
This section could also do with a little more explanation; {gratia} (and hence I) tens to consider differences of smooths to exclude the groups means. Here, if I read the paper and the code correctly, you included the group means. This works OK for simple models like this, but what if you had two or more parametric factor terms in the model? Then you would not (at least by default) have any way to isolate the group means for the by factor independently of the levels of the other factor. You would have to create differences conditional upon a level of
the other factor. Users, however, tend to expect differences to include the group means, as you have chosen to present things here. Hence a note exp


## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

# Appendix

## Reviewer's Comments

In the appendix I think you are needlessly restricting the size of the basis dimension to be k = 5, hence 4 basis functions per smooth when identifiability constraints are applied. Is there a reason I’m seeing here why you could leave this at the default k = 10 and really see the effect of the shrinkage as the EDF of the resulting smooths should be similar to the EDF you have with k = 5? This would also likely help with the k-index being low because there’s not a lot of shrinkage you can do when the maximum EDF possible is 4 (per smooth).

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

In L367 it is indicated that the simulated data used to fit the GAM that the reviewer alludes to has only 5 unique covariates (days 0, 2, 5, 7 and 10). The computational requisite in the smooth estimation of having the maximum number of basis equal to the number of unique values in the covariate makes it impossible to fit a GAM with a k>5, as the error "A term has fewer unique covariate combinations than specified maximum degrees of freedom" is thrown by _mgcv_. We consider that because the k-index for the model is 1.04 the basis dimension for the smooth is adequate (Wood says that "the further below 1 this is, th emore likely it is that there is missed pattern left in the residuals").

## Reviewer's Comments

Why change the model object name notation here? You had gam_00 previously and now you call the model m1? As you are already showing appraise() output for the diagnostic plots, you could use check.k() from {mgcv} to just get the basis dimension check.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

- The name of the model has been changed to `gam_02`, and it appears with this notation in Section 6.2, L383 so it matches the workflow of model selection presented in the Appendix.
- Additionally, we have used some of the source code of the function `gam.check` in order to use the graphical output of `gratia` and the numerical diagnostic information of `gam.check` without repeating the diagnostic plots.

# Suggested Changes

## Reviewer's Comments

Essentially now that we have knot-free splines, we can focus on the concept of the user’s prior for the upper limit on the wiggliness of the each smooth; this is set using k. You also should explain that we need to increase k a little above this prior expectation because the basis of dimension k + K has a richer set of functions of complexity k than a basis of dimension k. From a practical point of view, the user really only needs to think about some anticipated amount of wiggliness and set k to be a little larger than this, then fit the model.
Next the user should do the check.k() test on the size of the basis to see if it was large enough. If it isn’t, consider increasing k a bit and then refit and recheck k. Rinse and repeat.

Beyond the usual model diagnostics and choosing the conditional distribution of the response, that’s all the user really needs to do to get fitting GAMs. And this basic concept is largely missing from the manuscript and the worked tutorial.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}


## Reviewer's Comments

For the Appendix, I would suggest that you break up the code a bit to include a little narrative code explaining what each sub-chunk is doing. At the moment you have these monolithic blocks of code that produce a figure and/or some
printed console output and the user is largely left to figure out what the code is doing. I appreciate that there are comments, but for a tutorial, it would be better to have something more like a vignette rather than monolithic code
blocks with comments.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}


# Figures

## Reviewer's Comments

The figures are too tall — the aspect ratio used for the individual panels is wrong. You should be emphasizing the time axis so you should have individual panels that are wider than they are tall.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

We appreciate this comment regarding figure aesthetics, we have now made the figures wider to emphasize the time axis.

## Reviewer's Comments

Figure 3: on panel A, are the solid lines the truth in the main panel? If they are, you don’t need the inset plot, and if they aren’t, are they the mean of the simulated observations? If they are this latter, I think this is superfluous and it would be better to make the solid line the truth, about which you simulated noisy data.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

Although data simulation is a very common practice in Statistics/Ecology, it not so much in biomedical research. The main goal of Figure 3 A is to show that simulation is indeed a plausible tool to explore data behavior and to test statistical models in biomedical research. It might seem too basic or repetitive, but we are trying to convince the reader that simulation can indeed produce synthetic data that can be useful.

# Figures

## Reviewer's Comments

The figures are too tall — the aspect ratio used for the individual panels is wrong. You should be emphasising the time axis so you should have individual panels that are wider than they are tall.

Figure 3: on panel A, are the solid lines the truth in the main panel? If they are, you don’t need the inset plot, and if they aren’t, are they the mean of the simulated observations? If they are this latter, I think this is superfluous and it would be better to make the solid line the truth, about which you simulated noisy data.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

We have changed the aspect of the figures to emphasize the time axis, making them wider.

On Figure 3, we have added the original data to panel A, which now displays both the simulated data (thin lines) and the original data (truth) in order to simplify the figure. We have updated also places in the manuscript that reference this Figure as well.


# Minor Comments

## Reviewer's Comments

L57 _p_ values cannot be significant or otherwise, they just are. They might indicate statistically significant effects, where the weight of evidence against the null hypothesis is sufficient to meet some threshold of “significance”. I note the use of scare quotes so perhaps this sentence was intended in jest but even
so it is confusing and unnecessary. 

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

We appreciate the reviewer's comments here. However, the indicated sentence is not intended in jest. We are using in this sentence (and in the paper in general) a statistical approach that is understandable by biomedical researchers in general. To this day, the field values "significance" (defined by the arbitrarily set threshold of _p_<0.05). We are trying to convince the reader that low _p-values_ are possible with ill-fitted models, and we use language that is understandable by the reader.

## Reviewer's Comments

Also here we have “non-linear data” which almost surely should be “non-linear effects” — data aren’t non-linear, but relationships between variables, “effects”, might be. See also L316

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

We have changed the expression to "data that shows non-linear trends". The change has also been applied to L316 which is now L334 in the revised manuscript.

## Reviewer's Comments

L93 “distribution of the errors of the random effects” makes no sense. Also LMMs do not restrict random effects to be i.i.d. Gaussian — they could be i.i.d. gamma or t distributed for example. That typical R software (and mgcv from the GAM side) makes an assumption that the distribution of individual random effects terms is Gaussian, doesn’t mean the model class is so restricted.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

- We have changed the sentence to "the distribution of the random effects, which need to be independent", which also indicates that errors need not be normally-distributed.

## Reviewer's Comments

L185 here and throughout, check for situations where you have combined numerical citations to literature within narrative text; Here it should be “…see refs 40 & 42.)” for example, not superscript numerals.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

**leave this to the end as it can be fixed in the final .tex document**

## Reviewer's Comments

L244 “global” is perhaps more conventionally described as “population” in the mixed model literature.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

We have changed the word from  "global" to "population".

## Reviewer's Comments

L283 I think it is better to say “…the mathematical space within which the true but unknown $f(x_t)$ is thought to exist.”

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

We have updated this line to "the mathematical space within which the true but unknown $f(x_t\mid \beta_j)$  is thought to exist", in L290 in the revised manuscript.

## Reviewer's Comments

L293 You never really describe what “data-drive flexibility” is. Why are GAMs data driven and LMMs and GLMs not? This is a critical concept to convey I feel.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

This line has been removed from the revised manuscript. However, we acknowledge that we didn't clearly conveyed this point to the read. In Section 6 (Discussion, L525-526 we now clearly state that a major advantage of GAMs is that they can learn non-linear trends from the data, thus eliminating the requirement of other models such as LMEMs where the relationship needs to be provided.

## Reviewer's Comments

L351 Better to say “separate smooths” not “independent”. These factor-by smooths share a common basis, they just get an entirely separate set of model coeficients and smoothness parameters for each level of the factor.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

The sentence now reads "separate smooths for..."

## Reviewer's Comments

L354 “difference between group means” because the smooth encodes differences between the groups too, just not difference in the means. Be a little more specific here.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

The sentence now reads "any differences between the group means".

## Reviewer's Comments

L356 use straight quotes in code, not curly ones. And speficy the `family` here?

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}


## Reviewer's Comments

L359 “contain the fitted” instead of “store the”

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

The sentence now reads "contains the fitted model".

## Reviewer's Comments

L360 Not “knots” - there are k-1 basis functions, but as described above, because this is a TPRS there are knots at the unique data values and then we decompose the full basis and take the required eigenvectors as the basis to use.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

The updated sentence now reads "using four basis functions (plus the intercept)".

## Reviewer's Comments

L362 why highlight Gaussian process smooths? They’re not as useful as they seem as you need to optimise the length scale parameter yourself as otherwise, especially for longitudinal data they aren’t great - the length scale is the largest separate in time of any pair of observations.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

For the length of the covariates explored in this paper TPRS are sufficient. However, we want to make clear to the reader that other types of splines that might be appropriate in each case are available. To acknowledge this, L390 in the updated manuscript now reads "(a description of all the available smooths can be found by typing `?mgcv::smooth.terms` in the Console)".

## Reviewer's Comments

L366 See also Matteo Fasiolo’s {mgcViz} package

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

We acknowledge the existence of Dr. Fasiolo's _mgcvViz_ package, but due to the introductory nature of this paper we prefer to focus only on _mgcv_ and _gratia_.

## Reviewer's Comments

L373 Do rm-ANOVA and LMMs require equally-spaced or complete observations?

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

Only rm-ANOVA requires equally-spaced and complete observations. To avoid confusion, the line now reads "Because GAMs do not require equally-spaced or complete observations for all subjects (as rm-ANOVA does)".


## Reviewer's Comments

L377 delete “total”

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

The word "total" has been removed. The sentence now reads "If 40% of the observations are randomly deleted..."

## Reviewer's Comments

L381 “little” -> “few”

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

The word "few" has been removed. The sentence now reads "...with as few as 4 observations per group..."

## Reviewer's Comments

L393 “observed difference is significant” (not “change”)

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

The sentence has been rewritten. It now reads "...the observed difference is significant..."

## Reviewer's Comments

Also, it is (exceedingly) unlikely to yield 0. Better to say that the estimated difference is unlikely to be distinguishable from 0.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}


## Reviewer's Comments

L410 This needs to be reworded as what is written can be read as any difference between the control and treatment (and there is a difference as the controls are higher than the treated group before day 3) where you mean that the treatment group is only higher than the control group post day 3.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

This was an unintentional mistake based on some previous simulation results. We have updated the paragraph, and it now reads "shows that the Control Group has higher $\mbox{StO}_2$ before day 3, and is able to estimate the change on day 3 where the Treatment Group becomes significant as the full dataset smooth pairwise comparison." The change acknowledges that Control was higher before day 3, and that the Treatment Group becomes significant after day 3.

## Reviewer's Comments

L441 Delete “significant” here - we estimate the difference of the effects (what you call “change”) and make inference using the uncertainty estimates of that difference. Perhaps you mean “identify” or similar instead of “estimate” here, instead.

## \textcolor{reviewersblue} {Reply to Reviewer's Comments}

We have made the appropriate changes. The sentence now reads "The model is therefore able to identify changes between the groups at time points..."



