---
title: "Using generalized additive models to analyze biomedical non-linear longitudinal data: _Beyond Linear Mixed Models and Repeated Measures ANOVA_"
author:
- name: Ariel I. Mundo
  num: a
- name: Timothy J. Muldoon*
  num: a
- name: John R. Tipton
  num: b
address:
- num: a
  org: Department of Biomedical Engineering, University of Arkansas, Fayetteville, AR, US
- num: b
  org: Department of Mathematical Sciences, University of Arkansas, Fayetteville, AR, US
corres: "*Timothy J. Muldoon, Engineering Research Center Suite 2540, Fayetteville, AR, 72701 \\email{tmuldoon@uark.edu}"
presentaddress: This is sample for present address text this is sample for present address text
authormark: Mundo \emph{et al}.
articletype: Tutorial in Biostatistics
received: 
revised: 
accepted: 
abstract: "In biomedical research, the outcome of longitudinal studies has been traditionally analyzed using the _repeated measures analysis of variance_ (rm-ANOVA) or more recently, _linear mixed models_ (LMEMs). Although LMEMs are less restrictive than rm-ANOVA in terms of correlation and missing observations, both methodologies share an assumption of linearity in the measured response, which results in biased estimates and unreliable inference when they are used to analyze data where the trends are non-linear, which is a common occurrence in biomedical research. In contrast, _generalized additive models_ (GAMs) relax the linearity assumption, and allow the data to determine the fit of the model while permitting missing observations and different correlation structures. Therefore, GAMs present an excellent choice to analyze non-linear longitudinal data in the context of biomedical research. This paper summarizes the limitations of rm-ANOVA and LMEMs and uses simulated data to visually show how both methods produce biased estimates when used on non-linear data. We also present the basic theory of GAMs, and using trends of oxygen saturation in tumors reported in the biomedical literature, we simulate example longitudinal data (2 treatment groups, 10 subjects per group, 5 repeated measures for each group) to demonstrate how these models can be computationally implemented. We show that GAMs are able to produce estimates that are consistent with the trends of biomedical non-linear data even in the case when missing observations exist (with 40% of the simulated observations missing), allowing reliable inference from the data. To make this work reproducible, the code and data used in this paper are available at: https://github.com/aimundo/GAMs-biomedical-research."
keywords: Longitudinal data; Biomedical data; Simulation; R;
bibliography: refs.bib
output:
  bookdown::pdf_book:
    pandoc_args: [ "--listings" ]
    base_format: rticles::sim_article
    keep_tex: yes
    fig_caption: yes
    includes:
      in_header: preamble.sty #LaTeX formatting options
---


```{r libraries, message = FALSE,include=FALSE}
#the packages needed to run the code

library(patchwork)
library(tidyverse)
library(mvnfast)
library(nlme)
library(mgcv)
library(gratia)
library(viridis)
set.seed(2021) #set seed for reproducibility

#knitr::opts_chunk$set(fig.pos = 'H', out.extra = "",error=TRUE)

#global themes for plotting
thm<-scale_color_viridis_d(option="turbo",begin=0,end=1)
thm1<-scale_fill_viridis_d(option="turbo",begin=0,end=1)#global theme for plotting

#thm<-scale_color_ghibli_d("MarnieMedium2",direction=-1) #global theme for plotting
#thm1<-scale_fill_ghibli_d("MarnieMedium2",direction=-1) #global theme for plotting

#this function will remove the default "author information" that is the Pandoc LaTeX template. Otherwise, and additional "and" will appear at the end of the author list.Or, the custom template that is in the YAML header and that has the "author" line deleted may be used as well. An explanation in detail is provided at:
#https://github.com/rstudio/bookdown/issues/1158
remove_author <- function(x) {
  # identify empty author line
  i <- grep("^\\\\author\\{\\}$", x)
  # be sure it is the one pandoc inserts
  if(length(i) != 0 && grepl('^\\\\date\\{', x[i+1])) x <- x[-i]
  x
}
options(bookdown.post.latex = remove_author)
```


```{r child='01-Background.Rmd'}
```

<!-- \FloatBarrier -->

```{r child='02-Challenges.Rmd'}
```

<!-- \FloatBarrier -->

```{r child='03-GAM Theory.Rmd'}
```

<!-- \FloatBarrier -->

```{r child='04-Longitudinal analysis with GAMs.Rmd'}
```

<!-- \FloatBarrier -->

```{r child='05-Discussion.Rmd'}
```

<!-- \FloatBarrier -->

```{r child='06-Conclusion.Rmd'}
```

<!-- \FloatBarrier -->

# Supplementary Materials {-}

An Appendix which contains all the code used to create this manuscript, along with a basic workflow to implement GAMs in R is available as Supplementary Material in PDF. A GitHub repository containing all the code used for this paper along with detailed instructions for its use is available at https://github.com/aimundo/GAMs-biomedical-research.

***

\newpage
# References

<div id="refs"></div>



<!-- ```{r child='07-Appendix.Rmd'} -->

<!-- ``` -->


