---
title: |
    | **Using generalized additive models to analyze biomedical non-linear longitudinal data**
    | _Supplementary Material: Appendix_
subtitle: Mundo et. al.
header-includes:
    \usepackage{placeins}
output:  
  bookdown::pdf_document2:
    #template: my-template.tex #if a custom template that removes the additional "and" in the author information is desired
    pandoc_args: --listings #calls the listings package to fit code within the page margins
    keep_tex: yes #keep LaTeX file for submission
    fig_caption: yes #allows captions in figures
    toc: false #do not include table of contents
    extra_dependencies:
      subfig: null #allows for subfigures
      breqn: null #line breaks for long equations
      caption: ["font={small}"] #size of the figure captions
      float: null #allows for control of placement of figures
    includes:
      in_header: preamble_Appendix.sty #additional LaTeX formatting
  bookdown::word_document2:
    fig_caption: yes #figure caption
    keep_md: yes
  bookdown::html_document2:
    css: "style.css" #style for the HTML document
#csl: elsevier-with-titles.csl #style for references
#bibliography: refs.bib #references
#link-citations: yes #adds links to the citations
'': default
---



```{r libraries, message = FALSE,include=FALSE}
#the packages needed to run the code

library(patchwork)
library(tidyverse)
library(mvnfast)
library(nlme)
library(mgcv)
library(gratia)
library(viridis)
set.seed(2021) #set seed for reproducibility

knitr::opts_chunk$set(fig.pos = 'H', out.extra = "",error=TRUE)
#global themes for plotting
thm<-scale_color_viridis_d(option="turbo",begin=0,end=1)
thm1<-scale_fill_viridis_d(option="turbo",begin=0,end=1)#global theme for plotting
```

\newpage
```{r child='01-Background.Rmd'}
```

<!-- \FloatBarrier -->

```{r child='02-Challenges.Rmd'}
```

<!-- \FloatBarrier -->

```{r child='03-GAM Theory.Rmd'}
```

<!-- \FloatBarrier -->

```{r child='04-Longitudinal analysis with GAMs.Rmd'}
```

<!-- \FloatBarrier -->

```{r child='05-Discussion.Rmd'}
```

<!-- \FloatBarrier -->

```{r child='06-Conclusion.Rmd'}
```

<!-- \FloatBarrier -->


```{r child= '07-Appendix.Rmd'}
```

